// src/constants/pregnancyTips.ts
// 280 wellness tips for high-risk pregnancy monitoring
// Focused on hypertension, gestational diabetes, preeclampsia awareness, and maternal health
// Shown one per day in Dashboard

export const pregnancyTips: string[] = [
  // ---------- Days 1–93 ----------
  "Consistency matters — take your blood pressure at the same time each day for accurate tracking.",
  "Keep a water bottle with you always. Proper hydration helps regulate blood pressure naturally.",
  "Record any headaches in your app notes — even mild ones help your care team spot patterns.",
  "Rest your arm at heart level when taking BP readings for the most accurate results.",
  "Protein at every meal helps stabilize blood sugar and supports healthy fetal growth.",
  "Avoid crossing your legs during BP readings — it can falsely elevate your numbers.",
  "Track your weight weekly at the same time of day for consistent monitoring.",
  "Sudden swelling in your face or hands is a warning sign — contact your provider immediately.",
  "Deep breathing for 5 minutes before BP readings can help you get a calm, accurate result.",
  "Limit sodium to help manage blood pressure — aim for less than 2,300 mg daily.",
  "If you see spots or flashing lights, call your provider right away — don't wait.",
  "Small, frequent meals help prevent blood sugar spikes better than three large meals.",
  "Sit quietly for 5 minutes before taking your blood pressure — activity affects readings.",
  "Magnesium-rich foods like leafy greens and nuts support healthy blood pressure.",
  "Know your baseline BP numbers so you can recognize when something changes.",
  "Empty your bladder before BP readings — a full bladder can raise your numbers.",
  "Sudden weight gain of 2+ pounds in a day may indicate fluid retention — report it promptly.",
  "Potassium helps balance sodium — bananas, sweet potatoes, and beans are great sources.",
  "Upper abdominal pain, especially on the right side, needs immediate medical attention.",
  "Keep your BP monitor calibrated — bring it to appointments to compare with office readings.",
  "Walking 20-30 minutes daily can help manage both blood pressure and blood sugar.",
  "Avoid caffeine before BP readings — it can temporarily spike your numbers.",
  "If your systolic (top number) rises above your threshold, rest and recheck in 15 minutes.",
  "Gestational diabetes can be managed well with diet — work closely with your care team.",
  "Report any persistent headaches that don't respond to rest or approved pain relief.",
  "Fiber slows sugar absorption — aim for 25-30 grams daily from whole foods.",
  "Keep emergency contact numbers saved in your phone and posted at home.",
  "Check your feet daily for swelling — note if your shoes feel tighter than usual.",
  "Stress raises blood pressure — find calming activities that work for you.",
  "If monitoring glucose, test at consistent times relative to meals for meaningful trends.",
  "Your care team wants to hear from you — never hesitate to call with concerns.",
  "Protein paired with carbs prevents blood sugar spikes — try apple slices with nut butter.",
  "Know the signs of preeclampsia: severe headache, vision changes, upper belly pain, sudden swelling.",
  "Sleep on your left side to improve blood flow to your baby and reduce BP.",
  "Complex carbs (whole grains, vegetables) are better than simple sugars for glucose control.",
  "Take readings in a quiet room — background stress can affect your blood pressure.",
  "Sudden shortness of breath or chest pain requires immediate emergency care.",
  "Keep a consistent sleep schedule — poor sleep can worsen blood pressure and glucose levels.",
  "Ice water can help reduce swelling — but sudden severe swelling needs medical attention.",
  "Know your diastolic (bottom number) threshold and what to do if you exceed it.",
  "Avoid processed foods — they're high in hidden sodium and sugars.",
  "Light stretching improves circulation without raising blood pressure dangerously.",
  "If your BP is elevated, lie on your left side for 15 minutes and recheck.",
  "Omega-3 fatty acids support heart health — consider salmon, walnuts, or flaxseed.",
  "Never skip medications prescribed for BP or diabetes without talking to your provider.",
  "Keep healthy snacks pre-portioned so you're not tempted by less healthy options.",
  "Your BP patterns over time matter more than any single reading — trust the trend.",
  "Report nausea and vomiting that seems worse than typical morning sickness.",
  "Gentle prenatal yoga can help lower stress and blood pressure safely.",
  "If you have diabetes, always carry a fast-acting glucose source for lows.",
  "Document everything — your notes help your care team make better decisions.",
  "Elevated BP plus protein in urine is a key preeclampsia indicator — stay vigilant.",
  "Limit fruit juice — it spikes blood sugar faster than whole fruit with fiber.",
  "Support stockings can help with leg swelling and circulation.",
  "Know the difference between normal pregnancy swelling and concerning edema.",
  "Your weight gain pattern matters — sudden jumps can indicate fluid retention.",
  "Almonds, walnuts, and seeds are heart-healthy snacks that won't spike blood sugar.",
  "Practice the 15-15 rule for low blood sugar: 15g carbs, wait 15 minutes, recheck.",
  "Warm baths are okay, but avoid hot tubs — overheating raises heart rate and BP.",
  "Nosebleeds can happen with high BP — if frequent, mention it to your provider.",
  "Meal planning reduces stress and helps you make healthier choices consistently.",
  "Keep your BP log up to date — patterns are crucial for managing your care.",
  "Tingling or numbness in hands may be carpal tunnel from swelling — common but trackable.",
  "Stay connected to your care team through your app — communication saves lives.",
  "If you feel 'off' but can't explain why, trust your instincts and call your provider.",
  "Avoid standing for long periods — it can increase swelling and fatigue.",
  "Whole grains keep you fuller longer and prevent blood sugar crashes.",
  "Your BP may naturally fluctuate during pregnancy — this is normal but stay vigilant.",
  "Keep your app notifications on so you don't miss important reminders.",
  "Calcium supports both your bones and healthy blood pressure — dairy or fortified alternatives help.",
  "Learn to recognize Braxton Hicks vs. real contractions — timing and intensity matter.",
  "High-risk pregnancy is manageable — millions of women have healthy babies with proper monitoring.",
  "Avoid lying flat on your back after 20 weeks — it can affect blood flow.",
  "Green leafy vegetables are nutrition powerhouses — low calorie, high benefit.",
  "Your care team has seen it all — no question is too small or embarrassing.",
  "Consistent monitoring is your superpower — early detection prevents complications.",
  "Avoid energy drinks — they can spike blood pressure and heart rate dangerously.",
  "If you miss a reading, don't double up — just continue your normal schedule.",
  "Lemon water can help with nausea and keeps you hydrated.",
  "Severe swelling plus headache plus vision changes = call your provider NOW.",
  "Gentle walks after meals help lower post-meal blood sugar naturally.",
  "You're not alone — reach out to support groups for high-risk pregnancy.",
  "Track patterns: Does your BP rise at certain times? After certain foods? Note it.",
  "Advocate for yourself — you know your body better than anyone.",
  "Eat the rainbow — colorful produce provides diverse nutrients and antioxidants.",
  "If your glucose readings are consistently high, your provider may adjust your plan.",
  "Elevate your feet when resting — it helps reduce swelling and improves comfort.",
  "Preeclampsia can develop suddenly even if previous readings were normal — stay consistent.",
  "Celebrate your commitment to monitoring — every reading is an act of love for your baby.",
  "Hydration affects everything: BP, glucose metabolism, energy, and amniotic fluid.",
  "Review your readings weekly to spot trends your care team should know about.",
  "Your consistency with monitoring is making a real difference in your care.",
  "Blood pressure can vary based on time of day — morning readings are often most reliable.",

  // ---------- Days 94–186 ----------
  "Your blood volume increases significantly during pregnancy — hydration is critical.",
  "Continue sleeping on your left side — it optimizes circulation as baby grows.",
  "If you feel dizzy when standing, rise slowly — blood pressure adjusts more slowly during pregnancy.",
  "Round ligament pain is normal — but sharp, persistent pain should be reported.",
  "Keep protein intake high — it supports baby's growth and helps stabilize your glucose.",
  "Your BP readings are valuable data — don't skip them even on busy days.",
  "Compression socks can help if you're on your feet a lot or traveling.",
  "If you have gestational diabetes, your monitoring routine is especially important — stay committed.",
  "Fetal movement patterns become important — discuss kick counting timing with your provider.",
  "Swelling in ankles and feet is common — but face and hand swelling needs attention.",
  "Iron needs increase during pregnancy — discuss supplements if you're feeling extra fatigued.",
  "Your baby can hear you — talking to them reduces stress for both of you.",
  "Hemorrhoids can happen with increased blood volume — fiber and hydration help prevent them.",
  "Keep snacks in your purse, car, and desk — blood sugar crashes can happen anywhere.",
  "Shortness of breath may increase as baby grows — but sudden breathlessness needs evaluation.",
  "Glucose monitoring after meals shows how specific foods affect YOUR body — learn your patterns.",
  "Prenatal massage can help with aches — ensure the therapist is trained for pregnancy.",
  "Your blood pressure cuff should fit properly — too tight or loose affects accuracy.",
  "Know your delivery hospital and discuss your birth preferences with your provider.",
  "Preeclampsia risk increases as pregnancy progresses — your vigilance matters.",
  "If headaches become more frequent or severe, document them and report promptly.",
  "Baby's movements should become more predictable — note any significant changes.",
  "Dental health affects pregnancy — gum disease is linked to preterm birth.",
  "Heartburn often increases during pregnancy — smaller meals and staying upright after eating help.",
  "Keep your glucose meter clean and calibrated for accurate readings.",
  "You're the expert on your own body — speak up if something feels wrong.",
  "Leg cramps at night? Stretch your calves before bed and stay hydrated.",
  "Your placenta is working hard — good nutrition and BP control support its function.",
  "If prescribed blood pressure medication, take it exactly as directed — consistency matters.",
  "Gestational diabetes often improves after delivery — but monitoring now protects baby.",
  "Avoid sugary drinks — they spike glucose without providing nutrition.",
  "Your care team relies on your data — accurate reporting leads to better care.",
  "Baby is developing rapidly — your healthy eating supports their growth.",
  "Watch for signs of urinary tract infections — they're more common and serious during pregnancy.",
  "Meditation apps can help lower stress and blood pressure in just minutes.",
  "If your BP is well-controlled, celebrate that success — your efforts are working!",
  "Protein in your urine is tested regularly — it's a key preeclampsia indicator.",
  "Carb counting becomes easier with practice — you'll learn what works for your body.",
  "Discuss kick counting guidelines with your provider — they'll tell you when to start.",
  "Know where your nearest hospital is, especially if you're traveling.",
  "Varicose veins may appear during pregnancy — support hose and leg elevation help.",
  "Blood pressure patterns can shift during pregnancy — stay consistent with monitoring.",
  "Stay active within your limits — movement helps everything from mood to circulation.",
  "If you're taking insulin, never adjust doses without consulting your provider.",
  "Baby responds to your glucose levels — stable blood sugar means stable baby.",
  "Belly support bands can relieve back pressure as your center of gravity shifts.",
  "Review warning signs with your partner so they can help monitor too.",
  "Increased vaginal discharge is normal — but report any that's colored, bloody, or foul-smelling.",
  "Practice labor breathing techniques — they also help manage daily stress and BP.",
  "Keep your medical records accessible — you may need them unexpectedly.",
  "If you need bed rest, your care team will guide you — follow their recommendations.",
  "Skin changes like darkening or stretch marks are normal — moisturize for comfort.",
  "Your baby's brain is developing rapidly — omega-3s and good nutrition support this.",
  "If glucose is hard to control, you're not failing — some bodies need more support.",
  "Water retention increases during pregnancy — reduce sodium but don't restrict fluids.",
  "Check in with your mental health — anxiety and depression affect physical health too.",
  "Plan for childcare help after delivery — you'll need recovery time.",
  "Review your birth preferences and discuss them with your provider.",
  "If you have questions about test results, ask — understanding reduces anxiety.",
  "Your amniotic fluid protects baby — staying hydrated keeps levels healthy.",
  "Every day of careful monitoring gets your baby closer to a healthy arrival.",
  "Nesting instincts may kick in — but don't overexert yourself with projects.",
  "If prescribed low-dose aspirin for preeclampsia prevention, take it consistently as directed.",
  "Note any visual changes, even subtle ones like sensitivity to light.",
  "Hormonal changes during pregnancy can affect insulin resistance — this is why GD develops.",
  "Your monitoring is protecting both you and your baby — keep it up.",
  "Start thinking about your hospital bag — gather items gradually so you're not rushed.",
  "If your BP rises consistently, your provider may adjust your care plan — trust the process.",
  "You're doing an incredible job managing a complex pregnancy — give yourself credit.",
  "Rest when you can — fatigue is real and your body is working overtime.",
  "If swelling doesn't improve overnight, or gets worse, report it.",
  "Stay vigilant as your pregnancy progresses — some risks increase over time.",
  "Your commitment to daily monitoring makes a real difference in outcomes.",
  "Knowledge is power — the more you understand your conditions, the better you can manage them.",
  "Baby recognizes your voice — that bond is already forming.",
  "Prepare questions for your next appointment — write them down so you don't forget.",
  "If you need to be hospitalized for monitoring, it's for safety — not failure.",
  "Light exercise like swimming takes pressure off joints while staying active.",
  "Review preeclampsia warning signs periodically — they're important to remember.",
  "Your scale readings matter — sudden increases can indicate fluid problems.",
  "Every week of monitoring is an achievement — celebrate your dedication.",

  // ---------- Days 187–280 ----------
  "As pregnancy progresses, monitoring becomes even more important.",
  "Baby is gaining weight — your nutrition directly feeds their growth.",
  "Blood pressure often changes in late pregnancy — stay extra vigilant.",
  "If your provider recommends kick counts, 10 movements in 2 hours is typically reassuring.",
  "If baby's movements decrease significantly, contact your provider immediately.",
  "Braxton Hicks contractions may increase — time them to distinguish from real labor.",
  "Your BP readings are crucial — preeclampsia risk is highest in late pregnancy.",
  "Rest on your left side as much as possible — it optimizes blood flow.",
  "Hospital bag should be packed and ready — include your BP monitor and glucose supplies.",
  "Swelling may increase but sudden severe swelling is always an emergency.",
  "Review signs of labor with your provider — know when to head to the hospital.",
  "If you have GD, baby may be larger — this can affect delivery planning.",
  "Your body is working incredibly hard — respect its need for rest.",
  "Late pregnancy fatigue is real — nap when you can without guilt.",
  "Know your hospital's contact number and your provider's after-hours line.",
  "If BP readings spike suddenly, don't wait for a pattern — call your provider.",
  "Baby's lungs are maturing — every day of healthy pregnancy counts.",
  "Protein intake remains crucial — aim for lean sources at every meal.",
  "Install the car seat before you need it — you'll need it before leaving the hospital.",
  "If you experience sudden severe headache, don't take medication first — call your provider.",
  "Preeclampsia can develop rapidly — trust any instinct that something is wrong.",
  "Continue glucose monitoring — gestational diabetes management protects baby until delivery.",
  "Pelvic pressure increases as baby moves lower — this is normal but uncomfortable.",
  "Keep your phone charged and with you — you may need to call for help.",
  "Discuss your birth plan with your partner and your care team.",
  "If you're induced for health reasons, it's to protect you and baby — trust the decision.",
  "Contractions that come regularly and get stronger may be real labor.",
  "Watch for fluid leakage — amniotic fluid is clear and odorless.",
  "Bloody show (mucus plug) can mean labor is approaching — but it's not an emergency alone.",
  "Your BP may be checked more frequently as delivery approaches — each reading matters.",
  "HELLP syndrome is a severe complication — upper right pain plus nausea needs immediate attention.",
  "Baby may have hiccups — it's normal and means their diaphragm is practicing.",
  "Double-check that your hospital bag is ready and accessible.",
  "Review your birth plan with your support person.",
  "Insomnia is common in late pregnancy — use the time for relaxation techniques.",
  "If prescribed magnesium sulfate during delivery, it prevents seizures — it's protective.",
  "Your glucose needs may change in late pregnancy — monitor closely and report changes.",
  "Steroid shots may be given if early delivery is expected — they help baby's lungs mature.",
  "Learn the stages of labor so you know what to expect.",
  "Keep snacks ready for early labor — you'll need energy for the work ahead.",
  "If your water breaks, note the time and color, then head to the hospital.",
  "Back labor is common if baby is posterior — position changes can help.",
  "Your support person should know warning signs too — brief them regularly.",
  "If scheduled for induction, follow pre-op instructions carefully.",
  "Epidurals are safe — pain relief is not weakness.",
  "C-sections may be recommended for health reasons — it's still birth, still valid.",
  "Baby's heart rate will be monitored during labor — this is standard for high-risk pregnancies.",
  "Stay hydrated during labor — ice chips count if you can't drink.",
  "Pushing stage can vary — your team will guide you through it.",
  "If baby needs NICU time, you'll still bond — it's a detour, not a destination.",
  "Skin-to-skin after birth regulates baby's temperature and blood sugar naturally.",
  "Your BP will be monitored after delivery too — preeclampsia can develop postpartum.",
  "Breastfeeding helps your uterus contract and can improve glucose control.",
  "Postpartum bleeding is normal — but soaking a pad in an hour is too much.",
  "Your BP may take weeks to normalize after delivery — keep monitoring at home.",
  "Baby blues are common — but persistent depression needs professional support.",
  "If you had GD, your glucose should normalize — but get tested at your postpartum visit.",
  "Rest is critical for recovery — accept help from everyone who offers.",
  "Your body did something incredible — healing takes time and patience.",
  "Watch for postpartum preeclampsia signs: severe headache, vision changes, swelling.",
  "Breastfeeding challenges are common — lactation consultants can help.",
  "Your baby's first pediatrician visit is important — keep that appointment.",
  "If you had a C-section, incision care is important — watch for infection signs.",
  "Constipation is common postpartum — fiber, fluids, and gentle movement help.",
  "Your emotions may be intense — hormone shifts plus sleep deprivation are real.",
  "Baby's weight may drop slightly after birth then rebound — this is normal.",
  "If breastfeeding affects your glucose, adjust snacks accordingly.",
  "Your BP readings postpartum help your care team adjust medications safely.",
  "Swelling can persist for weeks — continue elevating your feet when resting.",
  "Sleep when baby sleeps — rest when you can.",
  "Your postpartum checkup is important — don't skip it even if you feel fine.",
  "Blood clot risk is elevated postpartum — report leg pain, swelling, or redness.",
  "If you needed medication during pregnancy, discuss continuation with your provider.",
  "Newborn jaundice is common — your pediatrician will monitor bilirubin levels.",
  "Your baby's glucose may be monitored if you had GD — this is precautionary.",
  "Breastfeeding burns calories — you may need extra healthy snacks.",
  "Postpartum anxiety is as real as depression — racing thoughts or panic need attention.",
  "Your pelvic floor needs recovery time — avoid heavy lifting for several weeks.",
  "Baby's sleep patterns are erratic at first — this phase doesn't last forever.",
  "If you're bottle feeding, that's okay — fed is best.",
  "Your BP should trend down after delivery — if it rises postpartum, call your provider.",
  "Hemorrhoids often worsen after delivery — sitz baths and stool softeners help.",
  "Your body grew a human — changes are badges of honor.",
  "Partner support matters — communicate your needs clearly.",
  "Women with GD history should monitor glucose periodically long-term — discuss with your provider.",
  "Preeclampsia history increases future cardiovascular risk — lifelong heart health matters.",
  "Your baby is learning your face, voice, and smell — bonding happens in small moments.",
  "If nursing, discuss alcohol and medication timing with your provider.",
  "Postpartum hair loss around 3 months is normal — it grows back.",
  "Your first period postpartum may be irregular — this is expected.",
  "Keep up gentle walks as cleared by your provider — movement aids recovery.",
  "Watch baby for feeding cues: rooting, hand-sucking, fussiness before crying.",
  "You navigated a high-risk pregnancy — you are stronger than you know.",
  "Your care team is still available — reach out with any postpartum concerns.",
  "Baby's umbilical cord stump falls off in 1-2 weeks — keep it clean and dry.",
  "Your body needs time to heal internally — be patient with yourself.",
  "If you had high BP, discuss how it may affect future pregnancies with your provider.",
  "You monitored, advocated, and protected your baby — be proud of yourself. 💕",
];