// src/constants/pregnancyFacts.ts
// Pregnancy-aligned daily facts for the Dashboard hero card.
//
// dayFacts[0] = pregnancy day 1 ... dayFacts[293] = day 294 (42 weeks).
// Day of pregnancy is computed from the EDD: day = 280 - daysUntil(EDD).
// Beyond day 294 the app rotates through postpartumFacts indefinitely,
// since the app cannot know the actual delivery date.
//
// Content focus mirrors the patient population: hypertension/preeclampsia,
// pre-existing diabetes, gestational diabetes, plus week-accurate fetal
// development milestones. Facts pending clinical review by Trinity.

export const dayFacts: string[] = [
// Week 1 (days 1–7)
"Pregnancy weeks are counted from the first day of your last period — so during week 1, your body is just preparing the way.",
"Starting a prenatal vitamin with folic acid now supports your baby's brain and spine before you even conceive.",
"Early blood pressure readings create your personal baseline — they help your care team spot meaningful changes later in pregnancy.",
"Take your blood pressure seated, feet flat on the floor, after five quiet minutes — good habits now mean reliable numbers all pregnancy.",
"If you have diabetes, steady glucose before conception and in the earliest weeks gives your baby the healthiest possible start.",
"Aim for 8 to 10 cups of water a day — hydration supports the rising blood volume pregnancy will soon demand.",
"Weigh yourself at the same time of day in similar clothing — consistent conditions make your weight trend meaningful.",
// Week 2 (days 8–14)
"This week your body prepares to ovulate — the egg your baby will grow from is maturing right now.",
"Limit caffeine to about one 12-ounce cup of coffee daily — a simple early swap that benefits the whole pregnancy.",
"Your uterine lining is thickening this week, building a nourishing home for a fertilized egg.",
"Morning blood pressure readings, before coffee or breakfast, give the cleanest picture of your resting numbers.",
"With pre-existing diabetes, share your glucose log with your care team early — small adjustments now protect the critical weeks ahead.",
"Gentle daily movement like a 20-minute walk supports both healthy blood pressure and steady blood sugar.",
"Ovulation typically happens around the end of week 2 — conception may be just days away.",
// Week 3 (days 15–21)
"Fertilization likely happens this week — a single cell now carries your baby's complete genetic blueprint.",
"This week begins organogenesis, the stage when your baby's organs start forming — the most delicate phase of development.",
"Tight glucose control matters most right now — your baby's organs are forming, and steady blood sugar protects that process.",
"The fertilized egg is dividing rapidly as it travels toward your uterus — implantation is only days away.",
"Skip alcohol completely — there is no known safe amount during pregnancy, especially while organs are forming.",
"Log every blood pressure reading, even the good ones — trends tell your care team more than any single number.",
"Some women notice light spotting as the embryo implants — mention any bleeding to your provider to be safe.",
// Week 4 (days 22–28)
"Your baby is now a blastocyst nestling into your uterine wall, and the placenta is beginning to form.",
"A home pregnancy test may turn positive this week as hCG rises — call your provider to schedule your first visit.",
"Your baby's neural tube, the start of the brain and spinal cord, begins forming — the folic acid in your prenatal vitamin supports it.",
"If you have diabetes, this is the week to tell your care team you're pregnant — early glucose fine-tuning shields forming organs.",
"Blood pressure naturally dips a bit in early pregnancy — your baseline readings help your care team know what's normal for you.",
"Fatigue this week is real — rising progesterone is hard work. Rest counts as taking care of your baby.",
"The amniotic sac and yolk sac are forming, cushioning and feeding your baby until the placenta takes over.",
// Week 5 (days 29–35)
"This week your baby's heart begins to beat — tiny cells contracting in rhythm for the very first time.",
"Your baby is about the size of a sesame seed, and the brain, spinal cord, and heart are all taking shape.",
"High glucose during weeks 5 through 8 raises risks while the heart and spine form — test as often as your care team advises.",
"Nausea often starts around now — small, frequent meals and sipping fluids between meals can ease queasiness.",
"Rest your arm on a table at heart level when taking blood pressure — arm position alone can shift readings several points.",
"A severe headache with vision changes is never something to wait on — call your care team right away, any time of day.",
"The neural tube is closing this week — one more reason your daily prenatal vitamin is doing important work.",
// Week 6 (days 36–42)
"Around week 6, your baby's heartbeat may be detectable on ultrasound — often near 110 beats per minute and climbing.",
"Tiny buds that will become your baby's arms and legs are sprouting this week.",
"If morning sickness makes eating hard, keep bland snacks like crackers by the bed and nibble before getting up.",
"Gestational diabetes usually develops later in pregnancy, but risk factors like family history are worth discussing with your provider now.",
"Nausea plus glucose-lowering medication can mean low blood sugar — keep quick carbs nearby and tell your care team about any vomiting.",
"Avoid measuring blood pressure right after stairs or a stressful call — five calm minutes first keeps readings honest.",
"Your baby's facial features are forming — dark spots mark future eyes, and small pits will become nostrils.",
// Week 7 (days 43–49)
"Your baby's brain is growing rapidly this week, adding thousands of new cells every minute.",
"The umbilical cord is now fully formed — your baby's lifeline for oxygen and nutrients.",
"Frequent urination is normal as blood volume rises — but burning or pain warrants a call to your provider.",
"Pregnancy hormones can make glucose swing unpredictably in the first trimester — frequent checks help you and your care team stay ahead.",
"Use the same arm every time you measure blood pressure — readings can differ noticeably between arms.",
"Hands and feet are emerging as tiny paddles at the ends of your baby's limb buds.",
"Heavy bleeding with cramping always deserves an immediate call to your care team — never wait it out.",
// Week 8 (days 50–56)
"All of your baby's major organs have now begun to form — an incredible eight-week construction project.",
"Your baby's fingers and toes are forming this week, still gently webbed for now.",
"Your first prenatal visit often lands around now — bring your blood pressure and glucose logs from the app to share.",
"A1C goals are tighter in pregnancy than outside it — review your personal target with your care team.",
"Your baby is about the size of a raspberry and already moving, though it's far too early to feel.",
"Try two blood pressure readings a minute apart and note both — many care teams like the average for accuracy.",
"Food aversions are your hormones talking — eat what stays down now and revisit variety when nausea fades.",
// Week 9 (days 57–63)
"Your baby's tiny muscles are forming, and small spontaneous movements have already begun.",
"Essential organs like the heart and brain now have their basic structure and keep maturing from here.",
"Insulin needs often dip in the first trimester — report frequent low blood sugars to your care team promptly.",
"Your baby's earlobes and eyelids are taking shape — the eyelids will stay gently fused for several months.",
"A sudden jump above your usual blood pressure numbers deserves a same-day message to your care team.",
"Ginger tea or ginger chews can take the edge off nausea — check with your provider before adding any supplement.",
"Weight may hold steady or even dip slightly in the first trimester — tell your care team if you can't keep food down.",
// Week 10 (days 64–70)
"Milestone week — your baby graduates from embryo to fetus, with all vital organs formed and now simply growing.",
"Tiny tooth buds are forming under your baby's gums this week.",
"The most glucose-sensitive window of organ formation is closing — your steady blood sugar work these past weeks made a real difference.",
"Your baby's bones and cartilage are hardening, and little knees and ankles are taking shape.",
"The placenta's hormones will challenge your insulin more later on — that's why gestational diabetes screening waits until 24 to 28 weeks.",
"Cuff fit matters — a too-small cuff reads falsely high. Ask your care team to confirm your cuff size at your next visit.",
"Round ligament twinges can start as your uterus grows — but sharp, persistent, or one-sided pain still warrants a call.",
// Week 11 (days 71–77)
"Your baby can open and close tiny fists this week and swallow small sips of amniotic fluid.",
"Your baby's head makes up nearly half its length right now — the body will catch up over the coming months.",
"Tiny hiccups may have started — quiet practice for breathing that you won't feel for months yet.",
"Blood pressure often reaches its pregnancy low around now — keep logging so your care team sees your natural curve.",
"If you have diabetes, a session with a dietitian pays off — consistent carbohydrates at meals smooth glucose all trimester.",
"Constipation is common in pregnancy — fiber, fluids, and walking help. Ask your provider before using any laxative.",
"Dizziness when standing quickly is common as blood vessels relax — rise slowly, and report any fainting to your provider.",
// Week 12 (days 78–84)
"Fingernails are appearing on your baby's fingertips this week.",
"Your baby's reflexes are waking up — a gentle press on your belly may make the baby squirm, though you can't feel it yet.",
"Your baby's kidneys are starting to make urine, which becomes part of the amniotic fluid.",
"Many parents share their news after week 12, when the risk of miscarriage drops significantly.",
"Home readings often reveal pregnancy blood pressure problems earlier than office visits do — your daily habit is real prevention.",
"Delivered a baby over 9 pounds before, or have PCOS? Mention it — your provider may screen for gestational diabetes earlier.",
"Pregnancy can speed up eye changes when you have diabetes — ask your care team whether a dilated eye exam is due.",
// Week 13 (days 85–91)
"Your baby's vocal cords are forming this week — quiet preparation for that very first cry.",
"Fingerprints are forming on your baby's tiny fingertips — a pattern completely unique in the world.",
"Energy often returns as the first trimester ends — a gentle walk after meals helps both blood sugar and blood pressure.",
"Your baby's intestines, which developed partly inside the umbilical cord, are settling into the abdomen.",
"Never skip readings because you feel fine — high blood pressure in pregnancy is usually silent.",
"Sudden swelling of your face or hands, a severe headache, or vision changes — any one of these means call your care team now.",
"The second trimester begins soon — appetite often improves, so plan protein-forward snacks to keep blood sugar steady.",
// Week 14 (days 92–98)
"Welcome to the second trimester — your baby can now squint, frown, and maybe even suck a thumb.",
"Fine, soft hair called lanugo is beginning to cover your baby's body, helping regulate temperature.",
"Your baby is about the size of a lemon and growing fast — expect steadier weight gain from here on.",
"Insulin resistance rises as the placenta grows from here — expect your care team to revisit your glucose plan regularly.",
"Your first-trimester blood pressure trend is gold — it helps your care team catch early signals of preeclampsia.",
"Nosebleeds and tender gums are common as blood flow increases — mention heavy or frequent bleeding to your provider.",
"You've built a daily monitoring habit through 14 weeks — every reading you take helps your care team keep you and your baby safe.",

// Week 15 (days 99–105)
"Welcome to week 15 — your baby is about the size of an apple and can sense light through closed eyelids.",
"Your blood pressure often dips slightly in mid-pregnancy — keep taking daily readings so your care team sees the full picture.",
"Steady weight gain is normal now. Weigh yourself at the same time each morning for the most consistent tracking.",
"If you take insulin, your needs may start shifting this trimester — keep logging your numbers and share them with your care team.",
"Aim for 8 to 12 cups of water a day — good hydration supports your blood volume, which is expanding rapidly right now.",
"Your baby is practicing breathing motions this week, moving amniotic fluid in and out of tiny lungs.",
"A lower BP reading than usual can be normal in the second trimester — but dizziness or fainting is worth a call to your provider.",
// Week 16 (days 106–112)
"By week 16, your baby's tiny heart pumps about 25 quarts of blood a day — your daily readings help protect you both.",
"Some moms feel first flutters between weeks 16 and 22 — early movements can feel like bubbles or gentle taps.",
"Second trimester energy boost? Use it for a daily walk — regular movement helps with both blood pressure and blood sugar.",
"Managing pre-existing diabetes? Insulin resistance often climbs from here — expect your care team to adjust your plan as you go.",
"Your baby's ears are moving into their final position this week — sound perception is on the way.",
"Sudden weight jumps of more than 2 pounds in a week are worth mentioning to your care team.",
"Keep your BP cuff at heart level and sit quietly for 5 minutes before measuring — small habits make readings more accurate.",
// Week 17 (days 113–119)
"Week 17: your baby is building body fat, which will help with warmth and energy after birth.",
"Your heart is pumping up to 50 percent more blood than before pregnancy — one reason consistent BP tracking matters so much.",
"Craving sweets? Pair carbs with protein to keep blood sugar steadier — a habit that pays off before glucose screening.",
"Your baby's skeleton is changing from soft cartilage to bone — keep up your calcium from dairy, greens, or fortified foods.",
"Headaches happen in pregnancy, but a severe headache that won't quit deserves a call to your provider.",
"Round ligament pain — brief, sharp twinges when you move — is common now. Persistent or severe pain means call your care team.",
"Snack smart: keep protein-rich options like nuts, cheese, or Greek yogurt handy to steady energy and blood sugar.",
// Week 18 (days 120–126)
"Week 18 begins the window when many moms first feel baby move — those gentle flutters are called quickening.",
"Your baby can now yawn, hiccup, and swallow — you might feel rhythmic little hiccups soon.",
"Your anatomy scan is coming up around week 20 — a detailed ultrasound of your baby's organs and growth.",
"Dizzy when standing up? Rise slowly — blood pressure often runs lower in mid-pregnancy.",
"If you use insulin, don't be surprised if doses need to rise — pregnancy hormones increase insulin resistance week by week.",
"Your baby's ears now stand out from the head, and the structures for hearing are maturing quickly.",
"Trends matter more than any single number — keep taking your BP at the same time every day.",
// Week 19 (days 127–133)
"Week 19: a protective coating called vernix now covers your baby's skin, like nature's moisturizer.",
"Not feeling movement yet? Still normal, especially in a first pregnancy — flutters may take a few more weeks.",
"About half of pregnancy weight gain typically happens after week 20 — steady, gradual gain is the goal.",
"Leg cramps at night are common — stretch your calves before bed and stay hydrated during the day.",
"Your baby's senses are wiring up this week — brain regions for taste, smell, hearing, vision, and touch are developing.",
"Blood sugar goals feel like a moving target? Hormones shift week to week — frequent checks help your care team keep pace.",
"Get familiar with your baseline BP numbers now — it makes any changes after week 20 much easier to spot.",
// Week 20 (days 134–140)
"Halfway there! Week 20 usually brings the anatomy scan — a detailed look at your baby's heart, brain, spine, and growth.",
"From week 20 on, sleep on your side — it improves blood flow to your baby and can help your blood pressure.",
"Preeclampsia risk begins after week 20 — your daily BP readings are your first line of defense.",
"Learn the preeclampsia warning signs: severe headache, vision changes, pain under your right ribs, and sudden swelling.",
"Your baby may respond to sounds now — a loud noise can make them startle or kick.",
"Sudden swelling in your face or hands — not just your feet — is a warning sign. Call your provider right away.",
"The glucose screening test is coming between weeks 24 and 28 — it checks how your body handles sugar during pregnancy.",
// Week 21 (days 141–147)
"Week 21: your baby's movements are getting stronger — flutters may become distinct kicks and rolls.",
"Your baby swallows amniotic fluid regularly now — flavors from your meals pass into it, shaping future taste preferences.",
"A reading of 140/90 or higher deserves a recheck after 5 quiet minutes — if it's still high, contact your care team.",
"Blurry vision, flashing lights, or spots after week 20 can signal preeclampsia — call your provider promptly.",
"Gestational diabetes often has no symptoms at all — that's exactly why the glucose screening test matters.",
"Fiber is your friend: whole grains, beans, and vegetables help steady blood sugar and ease constipation.",
"Rapid weight gain — more than about 2 pounds in a week — can be a preeclampsia clue. Daily weigh-ins help catch it early.",
// Week 22 (days 148–154)
"Week 22: your baby now looks like a miniature newborn, with eyebrows, eyelashes, and tiny fingernails.",
"Start noticing your baby's activity patterns — knowing what's normal for your baby helps you spot changes later.",
"The glucose screening is simple: a sweet drink, then a blood draw about an hour later. Quick, routine, and important.",
"Pain in your upper right belly, especially under the ribs, is a preeclampsia warning sign — don't wait it out. Call your provider.",
"Insulin needs often climb steeply between weeks 20 and 30 with pre-existing diabetes — rising doses mean the plan is working.",
"Swollen feet at day's end are common — swelling that arrives suddenly or includes your face and hands needs a call to your provider.",
"Your baby's grip is strong enough to grab the umbilical cord this week — hands and reflexes are developing fast.",
// Week 23 (days 155–161)
"Week 23: your baby's hearing is developing — the whoosh of your heartbeat and your voice are their daily soundtrack.",
"Talk, read, or sing to your bump — your voice is the sound your baby will know best at birth.",
"Don't skip your glucose screening — untreated gestational diabetes raises risks for you and baby, and treatment works.",
"No need to change how you eat before the glucose screen unless your provider says so — normal meals give the truest result.",
"A severe headache that doesn't ease with rest and fluids is a warning sign after week 20 — contact your care team.",
"Your baby's skin is still translucent, but fat is filling in — their weight will roughly double over the next month.",
"Breathless on the stairs? Your growing uterus crowds your lungs — but chest pain or sudden shortness of breath means call your provider now.",
// Week 24 (days 162–168)
"Week 24 is a milestone: your baby reaches viability, meaning survival is possible outside the womb with intensive care.",
"The glucose screening window opens now — weeks 24 to 28. Schedule yours if you haven't already.",
"Your baby's inner ear is maturing fast — a sudden sound may earn you a kick in response.",
"If your glucose screen comes back high, a longer follow-up test confirms things — one high screen isn't a diagnosis.",
"Your blood pressure may begin creeping back up from its mid-pregnancy dip — keep those daily readings coming.",
"Notice kicks most after meals or when you lie down? Those patterns are the beginning of movement awareness.",
"Gestational diabetes is manageable — most moms control it with diet changes, walking after meals, and glucose monitoring.",
// Week 25 (days 169–175)
"Week 25: your baby's nostrils open this week, and practice breathing ramps up.",
"Your baby's heart rate can change in response to your voice — calm talk can literally soothe them.",
"Diagnosed with gestational diabetes? A 10 to 15 minute walk after meals is one of the simplest ways to lower blood sugar.",
"Vision changes — blurriness, flashing lights, light sensitivity — after week 20 deserve a same-day call to your provider.",
"Sleep on your left side when you can — it eases pressure on the large vein returning blood to your heart.",
"With gestational diabetes, carbs aren't the enemy — pairing them with protein and spreading them through the day keeps sugar steadier.",
"Your baby's hands are fully developed this week, complete with one-of-a-kind fingerprints.",
// Week 26 (days 176–182)
"Week 26: your baby's eyes are forming their final structures and will open for the first time very soon.",
"Your baby's lungs are making surfactant now — the substance that will help them breathe air after birth.",
"Blood pressure trending up from its second-trimester low is expected — but readings at or above your thresholds mean call your care team.",
"If you're monitoring glucose, log readings alongside your meals — patterns tell your care team far more than single numbers.",
"Haven't done the glucose screen yet? Weeks 24 to 28 is the window — call your provider's office and get it on the calendar.",
"Some ankle swelling by evening is normal — sudden or one-sided leg swelling with pain is not. Call your provider.",
"Your baby startles at loud noises and settles at familiar voices — the outside world is coming into focus.",
// Week 27 (days 183–189)
"Week 27: your baby's eyes open this week — they'll practice blinking and can sense light and dark.",
"Your baby now has sleep and wake cycles — you may notice active stretches followed by quiet naps.",
"Kick counting starts soon: around week 28 you'll track how long it takes to feel 10 movements. Learn your baby's rhythm now.",
"Right upper belly pain along with headache or nausea after week 20 is a red-flag combination — contact your provider immediately.",
"Managing gestational diabetes? Keep meal times consistent — skipping meals can swing blood sugar in both directions.",
"With pre-existing diabetes, insulin needs often keep climbing into the third trimester — the steady rise now is expected.",
"Weigh in daily and watch the trend — gaining several pounds within a few days can signal fluid retention worth reporting.",
// Week 28 (days 190–196)
"Week 28: your baby weighs about 2 and a quarter pounds and can blink, dream, and respond to your voice.",
"This is the final week of the glucose screening window — if yours hasn't happened yet, make the call today.",
"From week 28, many providers recommend daily kick counts — ask your care team how they'd like you to track movement.",
"Preeclampsia can develop anytime from now until after delivery — keep up daily BP readings and never ignore warning signs.",
"A gestational diabetes diagnosis doesn't mean you did anything wrong — placental hormones drive it, and it's very manageable.",
"Sleep on your side, keep water within reach, and put your feet up when resting — small habits that support circulation now.",
"Severe headache, vision changes, right upper belly pain, or sudden swelling — any one of these means call your care team right away, day or night.",

// Week 29 (days 197–203)
"Welcome to week 29 — your baby weighs about 2.5 pounds and is getting stronger every day. Keep up your daily blood pressure readings.",
"Start counting kicks daily if you haven't already: pick a time when baby is active and count 10 movements. Most babies get there within 2 hours.",
"Preeclampsia risk rises in the third trimester. Call your provider right away for severe headache, vision changes, or pain under your right ribs.",
"Your baby's brain is entering a major growth surge this trimester — it will nearly triple in weight by birth.",
"Insulin resistance climbs in the third trimester. If you have diabetes, don't be surprised if your numbers drift up — share your logs with your care team.",
"Weigh yourself at the same time each day. A sudden gain of 2 or more pounds in a day can signal fluid retention — tell your provider.",
"Baby's movements matter more than ever now. If kicks slow down or feel different from your baby's usual pattern, call your care team the same day.",
// Week 30 (days 204–210)
"At week 30, your baby's lungs are still maturing but practicing breathing movements. Every week from here helps them get stronger.",
"Braxton Hicks contractions are irregular, don't get closer together, and often ease with rest or water. True labor contractions keep building.",
"Sudden swelling in your face or hands is a warning sign — contact your provider immediately.",
"Glucose control now directly affects your baby's growth. Well-managed blood sugar helps prevent a larger baby and complications at delivery.",
"Your baby now sleeps and wakes in cycles. Learn their active times — that pattern is your baseline for kick counts.",
"Take your blood pressure seated, feet flat, after 5 minutes of rest. A consistent routine gives your care team the clearest picture.",
"Do your kick count today: 10 movements within 2 hours is reassuring. Fewer than that, or a big change in pattern, means call your provider.",
// Week 31 (days 211–217)
"Week 31: your baby is putting on fat and can turn their head from side to side. You may notice stronger, more defined kicks.",
"Vision changes — blurriness, flashing lights, or spots — can signal preeclampsia. Don't wait; call your care team right away.",
"If you use insulin, your needs may keep rising through week 36. That's expected — your care team will adjust your plan with you.",
"Shortness of breath when climbing stairs is common as your uterus crowds your lungs. Sudden or severe breathlessness, though, warrants a call.",
"Heartburn worse at night? Try smaller meals and staying upright after eating. Ask your provider before taking anything for it.",
"Keep taking your daily BP reading even when you feel fine — preeclampsia can develop without any symptoms you'd notice.",
"Think ahead: talk with your provider about your birth preferences and start drafting a simple, flexible birth plan.",
// Week 32 (days 218–224)
"At week 32, many babies start settling head-down in preparation for birth. There's still time if yours hasn't yet.",
"Your baby's lungs are producing more surfactant now, the substance that helps them breathe after birth. Weeks 32 to 36 are big for lung maturity.",
"Know the signs of preeclampsia: severe headache, vision changes, upper belly pain, sudden swelling. Any one of these means call your provider now.",
"A gain of 2 or more pounds in a single day is worth reporting — sudden weight jumps often reflect fluid, not food.",
"With gestational diabetes, checking your blood sugar as scheduled is one of the most powerful things you can do for your baby right now.",
"Your baby's kicks may feel more like rolls and stretches as space gets tight — that's normal. What matters is that movement stays regular.",
"Sleep on your side rather than your back — it improves blood flow to your baby and can help keep your blood pressure steadier.",
// Week 33 (days 225–231)
"Week 33: your baby's bones are hardening, though the skull stays soft and flexible for the journey through the birth canal.",
"Pain in your upper right belly, just under the ribs, can be a preeclampsia warning sign — call your care team promptly if you feel it.",
"Count kicks at the same time every day. A consistent routine makes it easier to notice if something changes.",
"If your provider has ordered growth ultrasounds because of diabetes or blood pressure, keep every appointment — they guide delivery planning.",
"Some ankle swelling by evening is common. Swelling that appears suddenly, or affects your face and hands, is different — report it right away.",
"Nesting energy or exhaustion — both are normal now. Rest when your body asks, and keep your daily readings on schedule.",
"True labor: contractions get longer, stronger, and closer together and don't stop when you rest. When in doubt, call — that's what your team is for.",
// Week 34 (days 232–238)
"At week 34, your baby's central nervous system and lungs are maturing fast. Babies born now generally do very well with a little support.",
"A headache that's severe, doesn't respond to rest, or comes with vision changes needs a call to your provider today — not tomorrow.",
"Insulin resistance is near its peak. If your glucose numbers are harder to control, that's the pregnancy — not you. Loop in your care team.",
"Your baby now recognizes your voice. Talking, reading, or singing to them is real bonding time.",
"Keep your BP cuff in the same quiet spot and measure at the same time daily. Trends matter more than any single number.",
"Feeling more pelvic pressure? Baby may be settling lower. Regular painful tightening before 37 weeks should be reported promptly.",
"Line up your support: who's driving you to the hospital, who's watching pets or kids, and who to call first when labor starts.",
// Week 35 (days 239–245)
"Week 35: your baby's kidneys are fully developed and their liver is up and running. Weight gain is about half a pound a week now.",
"This is a good week to pack your hospital bag: ID, insurance card, phone charger, toiletries, comfortable clothes, and a going-home outfit for baby.",
"Preeclampsia can appear quickly, even late in pregnancy. Severe headache, vision changes, right upper belly pain, or sudden swelling — call immediately.",
"Pack your glucose meter and supplies in your hospital bag if you have diabetes — your care team will want your recent numbers too.",
"Do today's kick count. Ten movements in 2 hours is reassuring; a noticeable slowdown deserves a same-day call, even at night.",
"Think about cord blood banking now if you're interested — public donation and private banking both require arranging things before delivery.",
"Swelling plus a headache, or swelling plus a sudden weight jump, is a combination to report right away — don't wait for your next visit.",
// Week 36 (days 246–252)
"Week 36 usually brings the group B strep test — a simple swab. If positive, antibiotics during labor protect your baby. It's routine and very effective.",
"Weekly provider visits typically start now. Bring your BP log and any questions — these visits catch changes early.",
"Most babies are head-down by week 36. If yours is breech, your provider will talk through options — there's still time for baby to turn.",
"Your daily BP readings are most valuable in these final weeks — preeclampsia risk continues right up to and after delivery.",
"With diabetes, your provider may discuss delivery timing around weeks 37 to 39 depending on your glucose control and baby's growth. Ask what to expect.",
"Losing your mucus plug can happen days or weeks before labor. It's a sign of progress, not an emergency — mention it at your next visit.",
"Know your hospital route, where to park, and where to check in after hours. A little planning removes stress when the moment comes.",
// Week 37 (days 253–259)
"Week 37 is 'early term.' Your baby is nearly ready, but those last two weeks of brain and lung development still count.",
"If your water breaks — a gush or a steady trickle — note the time and color and call your provider right away, even without contractions.",
"Severe headache, vision changes, upper belly pain, trouble breathing, or sudden swelling: any of these means call your care team now.",
"Keep your kick counts going daily. Movement should stay regular right up to labor — babies don't 'run out of room' enough to stop moving.",
"If you have gestational diabetes, keep following your meal plan even as you're eager for delivery — steady glucose helps baby's transition after birth.",
"The classic hospital rule of thumb is 5-1-1: contractions 5 minutes apart, lasting 1 minute, for 1 hour — but follow your own provider's instructions.",
"Take your blood pressure today even amid the excitement. High readings in these final weeks need quick attention.",
// Week 38 (days 260–266)
"At week 38, your baby is shedding the fine lanugo hair and building fat for temperature control after birth.",
"Bloody show — pink or blood-tinged discharge — often means the cervix is changing. Bright red bleeding like a period is different: call right away.",
"Sudden swelling of your face or hands, or a 2-pound gain overnight, is a warning sign at any point — including now. Call your provider.",
"Restless nights are common now. Side-lying with a pillow between your knees can help — and rest counts even when sleep is short.",
"Diabetes tip for the home stretch: bring your glucose log to every weekly visit. It shapes decisions about delivery timing.",
"Contractions that fade when you change position or drink water are likely Braxton Hicks. Real labor doesn't care what position you're in.",
"Do your kick count and BP reading today. These two simple habits are your best early-warning system this close to delivery.",
// Week 39 (days 267–273)
"Week 39 is full term — your baby's brain, lungs, and liver are ready for life outside. Well done getting here.",
"Even at full term, preeclampsia risk continues. Severe headache, vision changes, or right upper belly pain still mean an immediate call.",
"Your provider may offer a cervical check this week. It's optional and doesn't predict exactly when labor will start — ask what's right for you.",
"Labor signs to know: regular contractions that intensify, water breaking, and persistent lower back pressure. When they arrive, call before you drive.",
"If you're on insulin or medication for diabetes, ask your care team how to handle doses once labor starts — get the plan in writing.",
"Movement still matters at full term. If baby's kicks slow down today, call your provider today — don't wait to see if tomorrow is better.",
"Keep the daily BP habit through delivery day. Blood pressure problems can surface for the first time even in the last days of pregnancy.",
// Week 40 (days 274–280)
"Week 40 — your due date week. Only about 1 in 20 babies arrives exactly on the due date, so keep your routines going.",
"Your placenta is still doing important work. Daily kick counts tell you it's doing its job — keep counting every day.",
"A due date is an estimate, not a deadline. Your provider will discuss monitoring and next steps if baby decides to linger.",
"Preeclampsia doesn't check the calendar. Severe headache, vision changes, sudden swelling, or belly pain — call immediately, due date or not.",
"With diabetes, going past your due date usually prompts a conversation about induction timing. It's a normal, planned discussion — bring your questions.",
"Walking, rest, and patience are all reasonable this week. Skip unproven labor-starting tricks without clearing them with your provider first.",
"Take today's blood pressure reading as usual. Your log from this week is especially useful if delivery planning conversations begin.",
// Week 41 (days 281–287)
"Going past your due date is common, especially with first babies. You're not overdue in a worrisome way yet — but monitoring steps up now.",
"Your provider may schedule non-stress tests this week — a belt monitors baby's heartbeat while you relax. It's painless and very reassuring.",
"Induction may come up now. Common steps include cervical ripening and IV medication to start contractions — ask your provider to walk you through it.",
"Kick counts are more important than ever past the due date. Any slowdown in movement deserves an immediate call, day or night.",
"Keep taking your daily blood pressure reading — preeclampsia can still develop after your due date, and quick reporting protects you both.",
"An ultrasound to check amniotic fluid is common this week. Normal fluid and a reactive non-stress test are strong signs baby is doing well.",
"Watch for labor signs and warning signs alike: regular contractions or water breaking mean call; severe headache or vision changes mean call now.",
// Week 42 (days 288–294)
"Week 42: most providers recommend delivery by now, since the placenta works less efficiently past 42 weeks. Induction is the safe, standard path.",
"If induction is scheduled, ask what to expect hour by hour — knowing the sequence makes the day feel far more manageable.",
"Monitoring is your safety net this week: non-stress tests, fluid checks, daily kick counts, and your daily BP reading all work together.",
"Preeclampsia risk continues past the due date and even after delivery. Severe headache, vision changes, or sudden swelling — call your care team now.",
"If you have diabetes, keep checking your glucose right up to delivery. Stable numbers now help your baby's blood sugar stay steady after birth.",
"Any decrease in your baby's movement this week is urgent — call your provider immediately rather than waiting for your next appointment.",
"You're in the final stretch. Keep your phone charged, your bag by the door, and your daily readings going — you'll be meeting your baby very soon.",

];

// Rotated daily once past day 294. No week references — must read
// correctly whether baby is a week old or three months old.
export const postpartumFacts: string[] = [
"Preeclampsia can develop up to 6 weeks after delivery — even if your blood pressure was normal your entire pregnancy. Keep taking your daily readings.",
"Rest is medicine right now — your body did something extraordinary, and healing takes weeks, not days.",
"Gestational diabetes raises your lifetime risk of type 2 diabetes — the postpartum glucose test is one of the most important appointments you'll keep.",
"A severe headache that won't ease up after delivery is a warning sign — call your provider or seek care right away.",
"Skin-to-skin contact calms your baby and can help steady your own stress hormones — it's good for both of you.",
"If you have diabetes, insulin needs often drop sharply after delivery — work closely with your care team on adjustments.",
"Baby blues — tearfulness and mood swings — are common early on. Feelings that last or feel heavier may be postpartum depression, and it's treatable.",
"Your daily readings still matter — they help your care team catch problems early while your body recovers.",
"Vision changes like blurriness, spots, or flashing lights after delivery are never normal — contact your care team immediately.",
"Drink water every time you sit down to feed your baby — hydration supports healing and recovery.",
"Don't skip the glucose test your provider schedules 4 to 12 weeks after delivery — it shows how your body handled gestational diabetes.",
"Soaking through a pad in an hour or passing large clots is heavy bleeding — call your provider right away.",
"Pain in your upper belly, especially on the right side, can signal postpartum preeclampsia — don't wait, call your provider.",
"Postpartum depression and anxiety are medical conditions, not weaknesses — tell your care team how you're really feeling.",
"Consistency matters — take your blood pressure at the same time each day, even with a newborn's unpredictable schedule.",
"Fever, chills, or worsening pain near an incision or tear can signal infection — contact your care team promptly.",
"Sudden swelling in your face or hands after delivery is a warning sign — reach out to your care team immediately.",
"Feeding challenges are common and help exists — lactation consultants and your care team are there for you.",
"Blood sugar can swing after delivery as hormones shift — check as often as your care team recommends and share anything surprising.",
"Gentle walks help circulation and mood, but ease in slowly — ask your provider before returning to exercise.",
"Delivery doesn't end preeclampsia risk. Your daily blood pressure readings are just as important now as they were before.",
"The postpartum checkup is where your provider looks at your blood pressure, healing, and emotional health — keep that appointment.",
"The healthy eating habits you built during pregnancy still protect you — balanced meals and regular movement lower your future diabetes risk.",
"Redness, warmth, or discharge around a C-section incision needs a provider's eyes — call sooner rather than later.",
"Shortness of breath after delivery deserves urgent attention — call your provider or seek care right away.",
"Sleep when your baby sleeps isn't a cliché — rest protects your blood pressure, your mood, and your healing.",
"If you feel constantly worried, can't sleep even when baby sleeps, or feel disconnected, reach out to your provider — treatment works.",
"Skipping meals while caring for a newborn can drop blood sugar fast — keep easy snacks within reach and ask your care team about a plan.",
"Postpartum preeclampsia often develops within the first days after delivery, but risk continues for six weeks — keep monitoring.",
"Every reading you sync gives your care team a clearer picture of your recovery — keep them coming.",
"Keep taking any blood pressure medication exactly as your provider prescribed — don't stop on your own, even if readings look good.",
"Leg pain, swelling in one leg, or warmth in your calf can signal a blood clot — call your provider right away.",
"Pain that gets worse instead of better as the days pass isn't something to push through — tell your provider.",
"A severe headache plus a high blood pressure reading is an emergency combination after delivery — seek care immediately.",
"Breastfeeding may help lower blood sugar and reduce future type 2 diabetes risk — ask your care team about support if you need it.",
"Checking in on your emotional health is as important as checking your blood pressure — your care team wants to know both.",
"Let others help with meals and chores so you can focus on two jobs: recovering and bonding with your baby.",
"Weight that climbs quickly over a few days can mean fluid retention — keep stepping on your scale and share the trend with your care team.",
"Night sweats are common as hormones reset — but a fever over 100.4°F warrants a call to your provider.",
"You don't need symptoms to develop postpartum preeclampsia — that's why daily blood pressure readings matter even when you feel fine.",
"If you ever have thoughts of harming yourself or your baby, seek help now — call your provider or dial 988. You are not alone, and this is treatable.",
"Your care team wants to hear from you — no question about your recovery is too small to call about.",

];