// src/constants/pregnancyTips.ts
// 280 friendly, supportive pregnancy & newborn wellness tips
// Shown one per day in Dashboard (Day 1–280)

export const pregnancyTips: string[] = [
  // ---------- 1st Trimester: Days 1–93 ----------
  "Day 1: Start taking a prenatal vitamin with folic acid — it helps your baby’s brain and spine develop.",
  "Day 2: Track your cycle or conception date to estimate your due date accurately.",
  "Day 3: Stay hydrated — water supports healthy cell growth for you and your baby.",
  "Day 4: Avoid smoking, alcohol, and recreational drugs — your baby’s organs are already forming.",
  "Day 5: Eat small, balanced meals to support early development and reduce nausea.",
  "Day 6: Begin gentle walks if your doctor agrees — it boosts energy and circulation.",
  "Day 7: Schedule your first prenatal visit to confirm pregnancy and discuss your care plan.",
  "Day 8: Keep healthy snacks handy — low blood sugar can make morning sickness worse.",
  "Day 9: Rest when you can. Your body is working hard building a tiny new life.",
  "Day 10: Limit caffeine to under 200 mg per day (about one small cup of coffee).",
  "Day 11: Add foods rich in iron like spinach or lentils — blood volume increases early in pregnancy.",
  "Day 12: Avoid cleaning litter boxes — cat feces can carry toxoplasmosis.",
  "Day 13: If you’re feeling emotional, it’s normal. Hormones are changing quickly.",
  "Day 14: A warm (not hot) bath can ease early pregnancy aches safely.",
  "Day 15: Focus on gentle stretching — it can help with early back tension.",
  "Day 16: Keep up with water — hydration helps reduce headaches and fatigue.",
  "Day 17: Try eating a small snack before bed to ease morning nausea.",
  "Day 18: Choose loose, comfortable clothing — bloating can start early.",
  "Day 19: Keep a pregnancy journal — it’s a beautiful way to remember your journey.",
  "Day 20: If nausea is severe, contact your provider — they can recommend safe remedies.",
  "Day 21: Balance rest and light activity to fight early fatigue.",
  "Day 22: Add a calcium source daily — baby’s bones begin forming soon.",
  "Day 23: Avoid unpasteurized cheese and deli meats to reduce risk of infection.",
  "Day 24: Try ginger tea or crackers for mild morning sickness relief.",
  "Day 25: Keep prenatal appointments on schedule — early care makes a difference.",
  "Day 26: Begin practicing deep breathing — it reduces anxiety and helps later in labor.",
  "Day 27: Stay positive — your baby senses your calm energy.",
  "Day 28: Stretch before bed to reduce leg cramps.",
  "Day 29: Start reading about healthy pregnancy nutrition — knowledge empowers you.",
  "Day 30: Sleep on your side when possible — it improves blood flow.",
  "Day 31: Reduce screen time before bed — it helps with pregnancy-related insomnia.",
  "Day 32: Add fruit and veggies in every meal — fiber helps prevent constipation.",
  "Day 33: Don’t skip meals — steady nutrients support baby’s steady growth.",
  "Day 34: Share your pregnancy news whenever you feel ready — no rush.",
  "Day 35: Listen to your body — fatigue means it’s time to rest.",
  "Day 36: Talk with your provider about safe exercise routines.",
  "Day 37: Light stretching or yoga can ease early pelvic tension.",
  "Day 38: Keep snacks like almonds handy for quick protein.",
  "Day 39: Start using a gentle moisturizer — skin stretches quickly.",
  "Day 40: Choose supportive shoes — balance shifts even early on.",
  "Day 41: Try lemon water to ease nausea naturally.",
  "Day 42: Don’t worry if symptoms come and go — it’s normal.",
  "Day 43: Celebrate small milestones — each week brings new growth.",
  "Day 44: Get plenty of sleep — your immune system works overtime.",
  "Day 45: Schedule your first ultrasound if you haven’t yet.",
  "Day 46: Avoid overheating — skip saunas and hot tubs.",
  "Day 47: Keep communication open with your healthcare provider.",
  "Day 48: Try to eat colorful foods — variety means better nutrition.",
  "Day 49: Practice gratitude daily — mental wellness matters too.",
  "Day 50: Learn your family’s medical history — it helps guide prenatal care.",
  "Day 51: Stay gentle with yourself — pregnancy is an adjustment.",
  "Day 52: Keep up your hydration — aim for 8–10 glasses of water.",
  "Day 53: Include whole grains for lasting energy.",
  "Day 54: Ask your provider before taking any herbal supplements.",
  "Day 55: Cravings happen — balance them with healthy choices.",
  "Day 56: Rest whenever your body says stop.",
  "Day 57: Celebrate the little heartbeat — life is growing inside you.",
  "Day 58: Support your back with a pillow while sitting.",
  "Day 59: Add vitamin D — sunlight or fortified foods help absorption.",
  "Day 60: You’re doing great — progress, not perfection!",
  "Day 61: Start gentle pelvic floor (Kegel) exercises for future support.",
  "Day 62: Avoid harsh cleaning chemicals; opt for natural options.",
  "Day 63: Enjoy a walk outdoors — fresh air reduces stress.",
  "Day 64: Ask your partner to join appointments — teamwork helps.",
  "Day 65: Write down questions for your next doctor visit.",
  "Day 66: Add a bit of protein with each snack — it balances blood sugar.",
  "Day 67: Plan your hydration: keep a water bottle nearby.",
  "Day 68: Slow down if you feel dizzy — low blood pressure is common.",
  "Day 69: Try not to stress over weight gain — focus on nourishment.",
  "Day 70: Take time for something that brings you joy today.",
  "Day 71: Review safe medications with your provider.",
  "Day 72: Keep a copy of emergency contact numbers handy.",
  "Day 73: Early prenatal testing may begin soon — it’s routine and optional.",
  "Day 74: Practice gentle mindfulness — pregnancy is a marathon, not a sprint.",
  "Day 75: Wear sunscreen — hormones make skin more sensitive to sun.",
  "Day 76: Eat slow and chew well to aid digestion.",
  "Day 77: Set small daily goals — progress builds confidence.",
  "Day 78: Join a pregnancy support group online or locally.",
  "Day 79: Drink water before meals to stay hydrated.",
  "Day 80: Be kind to your changing body — it’s doing something miraculous.",
  "Day 81: Limit stress — your calm helps your baby thrive.",
  "Day 82: Take your prenatal vitamin daily — consistency matters.",
  "Day 83: Plan balanced meals with carbs, protein, and veggies.",
  "Day 84: Ask your provider about prenatal screening options.",
  "Day 85: Light walks after meals aid digestion.",
  "Day 86: Keep light snacks by your bed — it helps morning nausea.",
  "Day 87: Pregnancy fatigue is real — rest without guilt.",
  "Day 88: Avoid heavy lifting to prevent strain.",
  "Day 89: Reflect on what’s going well — small wins matter.",
  "Day 90: Gentle stretching before bed relaxes muscles.",
  "Day 91: Baby’s organs are forming rapidly — keep up your nutrition!",
  "Day 92: Try prenatal yoga videos for comfort and calm.",
  "Day 93: You’re nearing the end of the first trimester — celebrate this milestone!",

  // ---------- 2nd Trimester: Days 94–186 ----------
  "Day 94: Energy often returns now — enjoy it but pace yourself.",
  "Day 95: Begin sleeping on your left side to improve circulation.",
  "Day 96: Start thinking about your birth plan — no rush, just ideas.",
  "Day 97: Protein needs rise — include eggs, beans, or lean meats daily.",
  "Day 98: Keep stretching — it helps reduce round ligament pain.",
  "Day 99: Add an extra pillow between your knees at night for comfort.",
  "Day 100: Feel flutters? Those tiny movements will grow stronger soon!",
  "Day 101: Baby’s senses are developing — music and your voice are soothing.",
  "Day 102: Stay hydrated to reduce dizziness and swelling.",
  "Day 103: Light swelling is normal; sudden swelling needs a doctor’s call.",
  "Day 104: Iron-rich meals prevent anemia — think spinach, lentils, or beef.",
  "Day 105: Schedule your mid-pregnancy anatomy scan.",
  "Day 106: Your belly is showing — embrace it proudly!",
  "Day 107: Keep snacks with protein and fiber handy.",
  "Day 108: Practice gentle pelvic tilts for lower back relief.",
  "Day 109: Start looking into childbirth education classes.",
  "Day 110: Talk openly with your provider about any new symptoms.",
  "Day 111: Moisturize your belly — stretching skin can feel itchy.",
  "Day 112: Add a rest break mid-day — energy naturally dips.",
  "Day 113: Plan maternity clothing that feels supportive and comfy.",
  "Day 114: Start light prenatal workouts if cleared by your provider.",
  "Day 115: Stay positive — second trimester is often the most comfortable phase.",
  "Day 116: Carry healthy snacks; hunger may appear suddenly now.",
  "Day 117: Write down your baby name ideas!",
  "Day 118: Keep practicing hydration — it’s the simplest self-care.",
  "Day 119: Try gentle foot massages to ease swelling.",
  "Day 120: If you notice headaches or vision changes, call your provider promptly.",
  "Day 121: Your baby hears your voice — talk, hum, or sing!",
  "Day 122: Eat calcium-rich foods to strengthen developing bones.",
  "Day 123: Add leafy greens for folate and fiber.",
  "Day 124: Take small breaks to stretch during work hours.",
  "Day 125: Practice slow breathing to relax tense muscles.",
  "Day 126: Prepare a bedtime ritual — good sleep supports growth.",
  "Day 127: Keep your posture upright — it eases back pressure.",
  "Day 128: Try prenatal massage if your provider approves.",
  "Day 129: Enjoy bonding time — your baby reacts to your mood.",
  "Day 130: Make sure your iron and vitamin D levels are checked.",
  "Day 131: Heartburn? Eat smaller meals and avoid lying down right after.",
  "Day 132: Enjoy fruits high in vitamin C — they help absorb iron.",
  "Day 133: Keep gentle movement part of your daily routine.",
  "Day 134: Don’t forget dental hygiene — gums are more sensitive now.",
  "Day 135: Hydrate before bed to prevent leg cramps.",
  "Day 136: Add slow belly breathing — it lowers blood pressure naturally.",
  "Day 137: If you feel light kicks — say hello back!",
  "Day 138: Update your doctor on any dizziness or swelling changes.",
  "Day 139: Plan a small getaway before the third trimester begins.",
  "Day 140: Keep track of your baby’s movements each day.",
  "Day 141: Include omega-3 rich foods for baby’s brain growth.",
  "Day 142: Rest your feet up after long standing hours.",
  "Day 143: A support pillow can make side sleeping cozy.",
  "Day 144: Add gentle upper-body stretches to open your chest.",
  "Day 145: Avoid crossing legs for long — promotes circulation.",
  "Day 146: Practice gratitude daily — your mindset shapes your journey.",
  "Day 147: Stay connected with supportive friends or family.",
  "Day 148: Keep stress levels low; deep breathing helps instantly.",
  "Day 149: Baby can hear loud noises — soothing sounds are best.",
  "Day 150: Continue regular checkups — monitor blood pressure and weight.",
  "Day 151: Light exercise improves sleep and mood.",
  "Day 152: Keep a small notebook of questions for appointments.",
  "Day 153: Notice changes in fetal movement — report major shifts.",
  "Day 154: Avoid standing for long without moving.",
  "Day 155: Drink water before and after walks to stay balanced.",
  "Day 156: Watch for Braxton Hicks — gentle tightening is normal.",
  "Day 157: Celebrate halfway — you’ve come so far!",
  "Day 158: Try prenatal meditation apps to calm your mind.",
  "Day 159: Practice slow stretches before bed.",
  "Day 160: Enjoy colorful produce — nutrients feed both of you.",
  "Day 161: Avoid sleeping flat on your back if possible.",
  "Day 162: Ask your provider about glucose screening timing.",
  "Day 163: Keep healthy snacks in your bag or car.",
  "Day 164: Write down things that make you smile today.",
  "Day 165: Bond with your baby through touch — gentle belly rubs are safe.",
  "Day 166: Wear supportive shoes; your joints loosen during pregnancy.",
  "Day 167: Balance rest with gentle movement.",
  "Day 168: Stay ahead of heartburn with smaller meals.",
  "Day 169: Share your excitement with someone you trust — joy multiplies.",
  "Day 170: Update your emergency contact list.",
  "Day 171: Hydration can ease Braxton Hicks contractions.",
  "Day 172: Practice saying “no” — your body’s energy is precious.",
  "Day 173: Review hospital or birth center options.",
  "Day 174: Enjoy nesting — small organizing tasks are satisfying.",
  "Day 175: Check that your vaccinations are up to date.",
  "Day 176: Start pelvic floor strengthening gently each day.",
  "Day 177: Begin thinking about maternity leave timing.",
  "Day 178: Wear breathable fabrics — pregnancy can raise body temp.",
  "Day 179: Balance rest days with light stretches.",
  "Day 180: Try sleeping with an extra pillow behind your back.",
  "Day 181: Add more whole grains — energy for baby’s growth.",
  "Day 182: Ask your provider about fetal kick counting.",
  "Day 183: If swelling worsens or vision blurs, contact your doctor immediately.",
  "Day 184: Plan a relaxing weekend — your body deserves it.",
  "Day 185: Eat slowly — it reduces heartburn and bloating.",
  "Day 186: You’re entering the third trimester — stay proud of your progress!",

  // ---------- 3rd Trimester: Days 187–280 ----------
  "Day 187: Your baby is gaining weight fast — keep balanced meals coming.",
  "Day 188: Prop your feet up daily to help circulation.",
  "Day 189: Practice labor breathing techniques now.",
  "Day 190: Ask about childbirth classes or hospital tours.",
  "Day 191: Pack light snacks with protein for steady energy.",
  "Day 192: Try warm (not hot) baths to relax sore muscles.",
  "Day 193: Discuss your birth preferences with your provider.",
  "Day 194: Practice sleeping on your left side for best oxygen flow.",
  "Day 195: Support your belly with a maternity band if needed.",
  "Day 196: Plan a simple hospital bag — essentials only.",
  "Day 197: If contractions become regular, time them calmly.",
  "Day 198: Eat small meals more often to reduce heartburn.",
  "Day 199: Your baby hears your voice clearly — talk often!",
  "Day 200: Drink water even when you don’t feel thirsty.",
  "Day 201: Gentle back rubs help with muscle tension.",
  "Day 202: Keep practicing Kegels — they help recovery too.",
  "Day 203: Rest often — sleep may get tricky later on.",
  "Day 204: Avoid lying flat on your back for long.",
  "Day 205: Discuss labor signs with your doctor so you know when to call.",
  "Day 206: Eat iron-rich foods to prevent fatigue.",
  "Day 207: Stay calm — anxiety can spike near delivery, but you’re prepared.",
  "Day 208: Gentle walks can encourage baby’s good position.",
  "Day 209: Keep snacks in your bag — blood sugar dips quickly now.",
  "Day 210: If swelling or headaches increase suddenly, call your provider.",
  "Day 211: Hydrate to avoid leg cramps at night.",
  "Day 212: Practice perineal massage if approved by your provider.",
  "Day 213: Baby hiccups? Totally normal — the diaphragm is strengthening.",
  "Day 214: Pack your hospital bag this week if you haven’t.",
  "Day 215: Review your birth plan with your partner.",
  "Day 216: Keep monitoring fetal movement daily.",
  "Day 217: Prepare the car seat — it must be installed before hospital discharge.",
  "Day 218: Limit sodium to reduce swelling.",
  "Day 219: Gentle prenatal yoga eases lower back strain.",
  "Day 220: If you feel contractions that don’t ease with rest, call your doctor.",
  "Day 221: Double-check childcare or support plans for after birth.",
  "Day 222: Keep communication open with your partner about delivery day.",
  "Day 223: Practice deep belly breathing to stay calm.",
  "Day 224: Write positive affirmations for labor day — they really help.",
  "Day 225: Drink water before bedtime to prevent dehydration overnight.",
  "Day 226: Avoid long car rides without breaks — stretch legs regularly.",
  "Day 227: If you notice fluid leakage, head to the hospital right away.",
  "Day 228: Stock up on easy, healthy freezer meals.",
  "Day 229: Talk to your provider about signs of preeclampsia.",
  "Day 230: Keep snacks and water on your nightstand — late pregnancy hunger is real.",
  "Day 231: Spend quiet time connecting with your baby.",
  "Day 232: Rest your wrists — pregnancy swelling can cause tingling.",
  "Day 233: Listen to your instincts — you know your body best.",
  "Day 234: Prepare a list of newborn essentials — less is more.",
  "Day 235: Ask your provider about postpartum recovery expectations.",
  "Day 236: Slow down — fatigue is your cue to rest deeply.",
  "Day 237: Keep a small fan or cool towel handy if you overheat.",
  "Day 238: Focus on calm, positive thoughts before bed.",
  "Day 239: Prepare for breastfeeding — learn basic latch techniques.",
  "Day 240: Discuss newborn care preferences with your provider.",
  "Day 241: Gentle stretching helps relieve hip tension.",
  "Day 242: Keep shoes easy to slip on — bending gets tricky now.",
  "Day 243: Practice short meditations — five minutes helps reduce stress.",
  "Day 244: Avoid skipping meals — steady energy helps baby grow.",
  "Day 245: Double-check your hospital paperwork and ID.",
  "Day 246: Rest between nesting bursts — balance activity with calm.",
  "Day 247: Keep your phone charged — you’re nearing delivery!",
  "Day 248: If you feel anxious, talk to someone — support matters.",
  "Day 249: Eat small meals with protein before bed to avoid dizziness.",
  "Day 250: Remember to pack comfy clothes for recovery.",
  "Day 251: Swelling is common — elevate legs when sitting.",
  "Day 252: Talk about pain management options ahead of time.",
  "Day 253: Practice timing contractions just to familiarize yourself.",
  "Day 254: Stay flexible — babies have their own timelines.",
  "Day 255: Keep contact numbers for your provider and hospital nearby.",
  "Day 256: Relax — your baby senses your calm confidence.",
  "Day 257: Drink electrolyte water if you’re feeling sluggish.",
  "Day 258: Prepare for postpartum support — meals, rest, and help matter.",
  "Day 259: If you feel fewer baby movements, call your doctor right away.",
  "Day 260: Slow walks can help your baby settle into position.",
  "Day 261: Practice your breathing — it helps during early labor.",
  "Day 262: You’re almost there — your body knows what to do.",
  "Day 263: Keep meals light and nourishing.",
  "Day 264: Nap whenever you can — rest is preparation.",
  "Day 265: Pack your charger, toiletries, and baby outfit for hospital.",
  "Day 266: Stay in touch with your doctor for any changes.",
  "Day 267: Talk about postpartum emotions — it’s okay to plan support early.",
  "Day 268: Drink plenty of fluids before delivery day.",
  "Day 269: Relax your shoulders — tension gathers there easily.",
  "Day 270: Practice patience — due dates are just estimates.",
  "Day 271: Visualize a calm, positive birth experience.",
  "Day 272: Double-check the car seat installation.",
  "Day 273: Take a warm shower and breathe — baby is almost here.",
  "Day 274: Keep your hospital bag by the door.",
  "Day 275: Rest, hydrate, and trust your instincts.",
  "Day 276: Notify your support team — the time is near.",
  "Day 277: Breathe deeply; you’ve nurtured life for nine months.",
  "Day 278: Review newborn safe sleep practices — back to sleep, firm surface.",
  "Day 279: Enjoy these last calm moments — life is about to change beautifully.",
  "Day 280: Congratulations — today may be the day you meet your baby! 💕"
];
